-- Create items table
CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  total_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for items table
ALTER TABLE items ENABLE ROW LEVEL SECURITY;

-- Create users_items table for tracking user commitments
CREATE TABLE IF NOT EXISTS users_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  item_id bigint REFERENCES items(id) NOT NULL,
  count integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, item_id)
);

-- Enable RLS for users_items table
ALTER TABLE users_items ENABLE ROW LEVEL SECURITY;

-- Create stored procedure for incrementing item counts
CREATE OR REPLACE FUNCTION increment_item_count(p_item_id bigint, p_count int)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE items
  SET total_count = total_count + p_count
  WHERE id = p_item_id;
END;
$$;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Enable read access for all users" ON items;
DROP POLICY IF EXISTS "Enable read access for own items" ON users_items;
DROP POLICY IF EXISTS "Enable insert access for own items" ON users_items;
DROP POLICY IF EXISTS "Enable update access for own items" ON users_items;

-- Create RLS policies
-- Items table policies
CREATE POLICY "Enable read access for all users"
  ON items FOR SELECT
  TO authenticated
  USING (true);

-- Users_items table policies
CREATE POLICY "Enable read access for own items"
  ON users_items FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Enable insert access for own items"
  ON users_items FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Enable update access for own items"
  ON users_items FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Insert sample items (only if they don't exist)
INSERT INTO items (name)
SELECT unnest(ARRAY[
  'Chips',
  'Salsa',
  'Guacamole',
  'Beer',
  'Wine',
  'Soda',
  'Ice',
  'Paper plates',
  'Plastic cups',
  'Napkins'
])
WHERE NOT EXISTS (SELECT 1 FROM items LIMIT 1);
